### PR TITLE
Enable formatting timestamp

### PR DESCRIPTION
**Pull request by wassimsalib**
It will be very helpful if we can format the timestamp, so I added a key in my config.log called `timestampFormat` which follows the same `moment` format http://momentjs.com/docs/#/parsing/string-format/

### CODE REVIEW

**Comment by ghaiklor** [comment]
@Kikobeats enable Travis and Coveralls for this repository. As I can see there is no errors but better to re-run tests with these changes.

**Comment by Kikobeats** [comment]
done. Do you need coveralls repo token?

**Comment by ghaiklor** [comment]
@Kikobeats no, make sure that Travis and Coveralls is enable - it's enough.

**Comment by Kikobeats** [comment]
They are enabled, I don't know why travis status is not present in the PR

**Comment by ghaiklor** [comment]
@wassimsalib you forgot to add moment to dependencies.
@Kikobeats that's why I asked to enable Travis and Coveralls long time ago :)

**Comment by ghaiklor** [comment]
@Kikobeats It will be available further

**Comment by ghaiklor** [comment]
@Kikobeats pushed fixed version, I think you can publish

**Comment by ghaiklor** [comment]
@Kikobeats still, I don't see is enabled - https://travis-ci.org/Kikobeats/sails-hook-winston

**Comment by Kikobeats** [comment]
@ghaiklor I think that you need push something to enable it

screen shot 2016-02-16 at 09 53 23

**Comment by Kikobeats** [comment]
@ghaiklor sorry Ia activate not, I confused with other sails repository 😅

**Comment by ghaiklor** [comment]
@Kikobeats check Coveralls too and I'll push something to enable builds.

**Comment by Kikobeats** [comment]
screen shot 2016-02-16 at 09 57 38

Add bagde:

```
[![Coverage Status](https://coveralls.io/repos/github/Kikobeats/sails-hook-winston/badge.svg?branch=master)](https://coveralls.io/github/Kikobeats/sails-hook-winston?branch=master)
```

**Comment by ghaiklor** [comment]
@Kikobeats you can publish update

**Pull request merged**
